Port {{ rdz_port }}
Match LocalPort {{ rdz_port }}
    AllowUsers {{ user }}
    PermitEmptyPasswords yes
    PasswordAuthentication yes
    ForceCommand cd {{ fitctf_dirpath }} && poetry run fit-rendezvous
